// Writeups will be loaded from writeups.json (generated by build.py)
let writeups = [];

// State
let currentView = 'home';
let selectedCtf = null;
let selectedCtfCategory = null;
let selectedHtbDifficulty = null;

// DOM Elements
const writeupsList = document.getElementById('writeups-list');
const categoriesNav = document.querySelector('.categories');

// Get unique CTF names
function getCtfNames() {
    return [...new Set(writeups.filter(w => w.ctf).map(w => w.ctf))];
}

// Get categories for a specific CTF (only non-null categories)
function getCtfCategories(ctfName) {
    return [...new Set(writeups.filter(w => w.ctf === ctfName && w.category !== null).map(w => w.category))];
}

// Check if CTF has categories or just direct writeups
function ctfHasCategories(ctfName) {
    return writeups.some(w => w.ctf === ctfName && w.category !== null);
}

// Get HTB difficulties (only non-null)
function getHtbDifficulties() {
    return [...new Set(writeups.filter(w => w.category === 'htb' && w.difficulty !== null).map(w => w.difficulty))];
}

// Check if HTB has difficulty folders
function htbHasDifficulties() {
    return writeups.some(w => w.category === 'htb' && w.difficulty !== null);
}

// Initialize
document.addEventListener('DOMContentLoaded', async () => {
    // Load writeups from JSON
    try {
        const response = await fetch('writeups.json');
        writeups = await response.json();
    } catch (error) {
        console.error('Failed to load writeups.json:', error);
        writeupsList.innerHTML = '<p class="loading">Run `python3 build.py` to generate writeups.json</p>';
        return;
    }

    const params = new URLSearchParams(window.location.search);
    const writeupFile = params.get('writeup');
    const ctf = params.get('ctf');
    const cat = params.get('cat');
    const htb = params.get('htb');

    if (writeupFile) {
        loadWriteup(writeupFile);
    } else if (htb) {
        selectedHtbDifficulty = htb;
        currentView = 'htb-writeups';
        renderView();
    } else if (ctf && cat) {
        selectedCtf = ctf;
        selectedCtfCategory = cat;
        currentView = 'ctf-writeups';
        renderView();
    } else if (ctf) {
        selectedCtf = ctf;
        // Check if this CTF has categories
        currentView = ctfHasCategories(ctf) ? 'ctf-categories' : 'ctf-direct';
        renderView();
    } else {
        renderView();
    }
});

// Render current view
function renderView() {
    categoriesNav.style.display = 'flex';

    categoriesNav.innerHTML = `
        <button class="category-btn ${currentView === 'home' ? 'active' : ''}" onclick="goHome()">All</button>
        <button class="category-btn ${currentView === 'htb' ? 'active' : ''}" onclick="showHtb()">HTB Machines</button>
        <button class="category-btn ${currentView.startsWith('ctf') ? 'active' : ''}" onclick="showCtfList()">CTF</button>
    `;

    switch (currentView) {
        case 'home':
            renderHome();
            break;
        case 'htb':
            renderHtb();
            break;
        case 'htb-difficulties':
            renderHtbDifficulties();
            break;
        case 'htb-writeups':
            renderHtbWriteups();
            break;
        case 'ctf-list':
            renderCtfList();
            break;
        case 'ctf-categories':
            renderCtfCategories();
            break;
        case 'ctf-writeups':
            renderCtfWriteups();
            break;
        case 'ctf-direct':
            renderCtfDirect();
            break;
    }
}

// Navigation functions
function goHome() {
    currentView = 'home';
    selectedCtf = null;
    selectedCtfCategory = null;
    history.pushState({}, '', 'index.html');
    renderView();
}


function showHtb() {
    selectedHtbDifficulty = null;
    // Check if HTB has difficulty folders
    if (htbHasDifficulties()) {
        currentView = 'htb-difficulties';
    } else {
        currentView = 'htb';
    }
    history.pushState({}, '', 'index.html');
    renderView();
}

function selectHtbDifficulty(difficulty) {
    selectedHtbDifficulty = difficulty;
    currentView = 'htb-writeups';
    history.pushState({}, '', `?htb=${difficulty}`);
    renderView();
}

function showCtfList() {
    currentView = 'ctf-list';
    selectedCtf = null;
    selectedCtfCategory = null;
    history.pushState({}, '', 'index.html');
    renderView();
}

function selectCtf(ctfName) {
    selectedCtf = ctfName;
    // Check if this CTF has category folders or direct writeups
    if (ctfHasCategories(ctfName)) {
        currentView = 'ctf-categories';
        history.pushState({}, '', `?ctf=${ctfName}`);
    } else {
        // No categories - show writeups directly
        currentView = 'ctf-direct';
        history.pushState({}, '', `?ctf=${ctfName}`);
    }
    renderView();
}

function selectCtfCategory(category) {
    selectedCtfCategory = category;
    currentView = 'ctf-writeups';
    history.pushState({}, '', `?ctf=${selectedCtf}&cat=${category}`);
    renderView();
}

// Render functions
function renderHome() {
    const htbDifficulties = getHtbDifficulties();
    const ctfNames = getCtfNames();

    // Order difficulties
    const order = ['easy', 'medium', 'hard', 'insane'];
    const sortedDiffs = htbDifficulties.sort((a, b) => order.indexOf(a) - order.indexOf(b));

    writeupsList.innerHTML = `
        <h2 class="section-title">HTB Machines</h2>
        ${sortedDiffs.length ? sortedDiffs.map(diff => `
            <div class="writeup-card" onclick="selectHtbDifficulty('${diff}')">
                <h3>${diff.toUpperCase()}</h3>
                <div class="meta">
                    <span class="tag ${diff}">${writeups.filter(w => w.category === 'htb' && w.difficulty === diff).length} machines</span>
                </div>
            </div>
        `).join('') : '<p class="loading">No HTB writeups yet.</p>'}
        
        <h2 class="section-title" style="margin-top: 2rem;">CTF Writeups</h2>
        ${ctfNames.length ? ctfNames.map(ctf => `
            <div class="writeup-card" onclick="selectCtf('${ctf}')">
                <h3>${ctf.toUpperCase()}</h3>
                <div class="meta">
                    <span class="tag ctf">${writeups.filter(w => w.ctf === ctf).length} writeups</span>
                </div>
            </div>
        `).join('') : '<p class="loading">No CTF writeups yet.</p>'}
    `;
}

function renderHtb() {
    const htbWriteups = writeups.filter(w => w.category === 'htb');
    if (htbWriteups.length === 0) {
        writeupsList.innerHTML = '<p class="loading">No HTB writeups yet.</p>';
        return;
    }
    writeupsList.innerHTML = htbWriteups.map(w => renderWriteupCard(w, w.difficulty || 'htb')).join('');
}

function renderHtbDifficulties() {
    const difficulties = getHtbDifficulties();
    // Order: easy, medium, hard, insane
    const order = ['easy', 'medium', 'hard', 'insane'];
    const sorted = difficulties.sort((a, b) => order.indexOf(a) - order.indexOf(b));

    writeupsList.innerHTML = `
        <h2 class="section-title">HTB Machines - Difficulty</h2>
        ${sorted.map(diff => `
            <div class="writeup-card" onclick="selectHtbDifficulty('${diff}')">
                <h3>${diff.toUpperCase()}</h3>
                <div class="meta">
                    <span class="tag ${diff}">${writeups.filter(w => w.category === 'htb' && w.difficulty === diff).length} machines</span>
                </div>
            </div>
        `).join('')}
    `;
}

function renderHtbWriteups() {
    const htbWriteups = writeups.filter(w => w.category === 'htb' && w.difficulty === selectedHtbDifficulty);
    writeupsList.innerHTML = `
        <a href="javascript:showHtb()" class="back-btn">← Back to difficulties</a>
        <h2 class="section-title">HTB - ${selectedHtbDifficulty.toUpperCase()}</h2>
        ${htbWriteups.map(w => renderWriteupCard(w, selectedHtbDifficulty)).join('')}
    `;
}

function renderCtfList() {
    const ctfNames = getCtfNames();
    if (ctfNames.length === 0) {
        writeupsList.innerHTML = '<p class="loading">No CTF writeups yet.</p>';
        return;
    }
    writeupsList.innerHTML = ctfNames.map(ctf => `
        <div class="writeup-card" onclick="selectCtf('${ctf}')">
            <h3>${ctf.toUpperCase()}</h3>
            <div class="meta">
                <span class="tag ctf">${writeups.filter(w => w.ctf === ctf).length} writeups</span>
            </div>
        </div>
    `).join('');
}

function renderCtfCategories() {
    const categories = getCtfCategories(selectedCtf);
    writeupsList.innerHTML = `
        <a href="javascript:showCtfList()" class="back-btn">← Back to CTFs</a>
        <h2 class="section-title">${selectedCtf.toUpperCase()} - Categories</h2>
        ${categories.map(cat => `
            <div class="writeup-card" onclick="selectCtfCategory('${cat}')">
                <h3>${cat.toUpperCase()}</h3>
                <div class="meta">
                    <span class="tag ${cat}">${writeups.filter(w => w.ctf === selectedCtf && w.category === cat).length} writeups</span>
                </div>
            </div>
        `).join('')}
    `;
}

function renderCtfWriteups() {
    const ctfWriteups = writeups.filter(w => w.ctf === selectedCtf && w.category === selectedCtfCategory);
    writeupsList.innerHTML = `
        <a href="javascript:selectCtf('${selectedCtf}')" class="back-btn">← Back to ${selectedCtf.toUpperCase()}</a>
        <h2 class="section-title">${selectedCtf.toUpperCase()} - ${selectedCtfCategory.toUpperCase()}</h2>
        ${ctfWriteups.map(w => renderWriteupCard(w, selectedCtfCategory)).join('')}
    `;
}

// For CTFs without category folders - show writeups directly
function renderCtfDirect() {
    const ctfWriteups = writeups.filter(w => w.ctf === selectedCtf);
    writeupsList.innerHTML = `
        <a href="javascript:showCtfList()" class="back-btn">← Back to CTFs</a>
        <h2 class="section-title">${selectedCtf.toUpperCase()}</h2>
        ${ctfWriteups.map(w => renderWriteupCard(w, 'ctf')).join('')}
    `;
}

function renderWriteupCard(writeup, tagType) {
    return `
        <a href="?writeup=${encodeURIComponent(writeup.file)}" class="writeup-card">
            <h3>${writeup.title}</h3>
            <div class="meta">
                <span class="tag ${tagType}">${tagType.toUpperCase()}</span>
            </div>
        </a>
    `;
}

// Load and render a single writeup
async function loadWriteup(filePath) {
    categoriesNav.style.display = 'none';
    writeupsList.innerHTML = '<p class="loading">Loading...</p>';

    try {
        const response = await fetch(filePath);
        if (!response.ok) throw new Error('Writeup not found');

        const markdown = await response.text();
        const writeup = writeups.find(w => w.file === filePath);
        const title = writeup?.title || filePath.split('/').pop().replace('.md', '');

        document.title = `${title} | jst3r's Writeups`;

        let backLink = 'index.html';
        let backText = 'Back to writeups';
        if (writeup?.ctf) {
            backLink = `?ctf=${writeup.ctf}&cat=${writeup.category}`;
            backText = `Back to ${writeup.ctf.toUpperCase()} / ${writeup.category.toUpperCase()}`;
        }

        writeupsList.innerHTML = `
            <a href="${backLink}" class="back-btn">← ${backText}</a>
            <article class="writeup-content">
                ${marked.parse(markdown)}
            </article>
        `;

    } catch (error) {
        writeupsList.innerHTML = `
            <a href="index.html" class="back-btn">← Back to writeups</a>
            <p class="loading">Failed to load writeup: ${error.message}</p>
        `;
    }
}
